version: '{build}'
pull_requests:
  do_not_increment_build_number: true
environment:
  matrix:
    - PYTHON: "C:\\Python37-x64\\python.exe"
      PYTHON_VERSION: "3.7"

    - PYTHON: "C:\\Python38-x64\\python.exe"
      PYTHON_VERSION: "3.8"
install:
  - cmd: "%PYTHON% -m pip install --upgrade pip"
  - cmd: "%PYTHON% -m pip install -r requirements.txt --upgrade"
  - cmd: "%PYTHON% -m pip install --upgrade cx_Freeze"
build_script:
  - cmd: "%PYTHON% setup.py build_exe"
artifacts:
  - path: "build\\exe.win-amd64-%PYTHON_VERSION%\\"
    name: "Berserker_Multiworld_%APPVEYOR_REPO_BRANCH%_%APPVEYOR_REPO_TAG%_Python%PYTHON_VERSION%-x64"
